import { Inter } from "next/font/google";
import "./globals.css";
import { CMDKProvider } from "@/context/cmdk2.context";
import CMDK from "@/components/cmdk/CMDK";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CMDKProvider>
          <CMDK />
          {children}
        </CMDKProvider>
      </body>
    </html>
  );
}
